//! Catalog app-api gateway route manifest (materialized from the authored
//! OpenAPI contract; business routes are protected by the default framework
//! profile, so dual-token auth is the manifest default).

use sdkwork_web_core::{HttpMethod, HttpRoute, HttpRouteManifest};

const HTTP_ROUTES: &[HttpRoute] = &[
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/attributes",
        "catalog",
        "attributes.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/categories",
        "catalog",
        "categories.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/categories/{categoryId}",
        "catalog",
        "categories.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/products",
        "catalog",
        "products.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/products/{productId}",
        "catalog",
        "products.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/products/{productId}/skus",
        "catalog",
        "products.skus.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/catalog/skus/{skuId}",
        "catalog",
        "skus.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/cart/items",
        "catalog",
        "items.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/cart/items",
        "catalog",
        "items.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/cart/items/{cartItemId}",
        "catalog",
        "items.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/cart/items/{cartItemId}",
        "catalog",
        "items.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/addresses",
        "catalog",
        "addresses.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/addresses",
        "catalog",
        "addresses.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/addresses/{addressId}",
        "catalog",
        "addresses.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/addresses/{addressId}",
        "catalog",
        "addresses.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Put,
        "/app/v3/api/addresses/{addressId}/default_selection",
        "catalog",
        "addresses.defaultSelection.update",
    ),
];

pub fn gateway_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(HTTP_ROUTES)
}
