//! Generated gateway bootstrap for sdkwork-catalog.
//! Regenerated by pnpm gateway:assembly:materialize.

use axum::Router;
use sdkwork_catalog_service_host::CatalogServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router() -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_catalog_app_api::gateway_mount(pool).await);
    router = router.merge(sdkwork_routes_catalog_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
