//! Generated gateway bootstrap for sdkwork-catalog.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_catalog_service_host::CatalogServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<CatalogServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(
        sdkwork_routes_catalog_app_api::build_catalog_app_router_with_framework(host.clone()).await,
    );
    router = router.merge(sdkwork_routes_catalog_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
